### ISSUE TITLE
the NOT_EMPTY validation not accept NEWLINE

### ISSUE THREAD

**Issue by fukhaos** [thyrlian/AwesomeValidation#16]
Not works in edittext with multiline.

**Comment by thyrlian** [comment]
@fukhaos Thank you for reporting :+1: 
But could you please be more specific - which input did you give for the multiline enabled EditText, and what do you expect (validation pass or fail)?  Thanks.

**Comment by fukhaos** [comment]
I type something like:
**Lorem ipsum dolor sit met,
consectetur adipiscing elit.**

and was validated like EMPTY.

I use this regex:
"^(\\s|\\S)*(\\S)+(\\s|\\S)*$"

and works.

**Comment by thyrlian** [comment]
@fukhaos you are right.

RegexTemplate.NOT_EMPTY doesn't work for this case (**multilines EditText**), sorry that I haven't considered it at the beginning.

And I've tried your regex, it doesn't really work either :(

So I'll try to find a working one later.  Thanks.

**Comment by thyrlian** [comment]
@fukhaos finally I spent some time and got it work.

The perfect regex for that should be: `(?m)^\\s*\\S+[\\s\\S]*$`

Please check the commit and corresponding unit tests (all are passed):
[NOT_EMPTY regex](https://github.com/thyrlian/AwesomeValidation/blob/7235a257c3b0462bed5c56c1577bda597021e431/library/src/main/java/com/basgeekball/awesomevalidation/utility/RegexTemplate.java#L5)
[UnitTest](https://github.com/thyrlian/AwesomeValidation/blob/7235a257c3b0462bed5c56c1577bda597021e431/library/src/test/java/com/basgeekball/awesomevalidation/utility/RegexTemplateTest.java#L9-L37)
