### ISSUE TITLE
remove guava from dependencies

### ISSUE THREAD

**Issue by gostik** [thyrlian/AwesomeValidation#17]
Hi! I think it would be better to remove heavy guava dependency from project, because it has more than 17000 methods

**Comment by thyrlian** [comment]
@gostik Yes, I totally understand your point.

1. It only uses **_Guava#Range_**, in that case, importing the complete Guava is way too heavy.  But at that moment I could not find a better alternative.
2. Long while ago, I heard that there was a tricky way to **partially import** Guava, but because it was more like a dirty hack, I didn't really want to try it out.

Still, I agree with you, but need a good solution.  Thanks :+1:

**Comment by gostik** [comment]
Thanks for your reply!
Recently  faced with well known 65500  methods exceed problem
When i've  started investigation i found guava dependency at this lib and more than 16000 methods there. So even you use only Guava#Range only anyway it add complete Guava library.
Ok, i will take a look later at your code more precisely! Thanks

**Comment by thyrlian** [comment]
I just tried [dexcount-gradle-plugin](https://github.com/KeepSafe/dexcount-gradle-plugin):
```
13666    3265     com.google
13649    3256     com.google.common
3        0        com.google.common.annotations
876      325      com.google.common.base
7        6        com.google.common.base.internal
849      282      com.google.common.cache
8231     1553     com.google.common.collect
74       29       com.google.common.escape
65       28       com.google.common.eventbus
490      120      com.google.common.hash
3        1        com.google.common.html
616      141      com.google.common.io
102      39       com.google.common.math
144      214      com.google.common.net
556      104      com.google.common.primitives
511      91       com.google.common.reflect
1125     324      com.google.common.util
1125     324      com.google.common.util.concurrent
4        5        com.google.common.xml
17       9        com.google.thirdparty
17       9        com.google.thirdparty.publicsuffix
```

Yes, Guava has 13666 methods.  I may try [shrinkGuava](https://github.com/ligi/shrinkGuava) later.

**Comment by gostik** [comment]
Thanks for your investigation!
yeap, i suppose it have a sense

**Comment by nisrulz** [comment]
This I just stumbled upon [this](http://seeds.tribe7.net/) .

Looks like we can use `seeds-collect` to replace the fat guava dependency.
 The only drawback is it was updated last 2 years back and is a derived from guava v16.0, where as the latest version of guava in use is 19.0.

**Comment by thyrlian** [comment]
Nice finding!  Thanks.

Unfortunately as you said the atomic library is not up-to-date, thus better not use it.

The best solution would be use some gradle / proguard tricks to extract necessary classes only, that's engineering perfect approach, and could be always up-to-date by just change the version number in configuration file.  But I don't know how to achieve that.

Other than that, we could also take the latest Range class out, pack it, and place the jar to the library's dependencies directory.  This manual way would work, but tedious.

**Comment by nisrulz** [comment]
Manual work is going to be a problem still because as it turns out the class `Range` includes `imports` which in turn include their own `imports`. You cannot simply isolate  the `Range` class.

Should be making a project to iterate over these via gradle tasks to verify the nested dependent classes and then package them into one, the same way I guess the other guy did. But here the requirement is of a specific class only. 

I can find a way of getting to build a guava-seed library whenever I get time , provided I have been working/building  android libraries lately.

**Comment by thyrlian** [comment]
Yes, I don't like the manual approach.  But in fact, it's not an endless work.  Since Guava#Range only refers to a few **Guava#base** classes, plus an **annotation** class, and all the referred base classes only refer to base classes inside the same package `com.google.common.base`, they're well organized.

**Comment by thyrlian** [comment]
With this [commit](https://github.com/thyrlian/AwesomeValidation/commit/182bfa56bc7e773dd96bf88691f6eba2561eb1e2), the unnecessary classes from Guava are now stripped off.

Here are the latest results from dexcount-gradle-plugin:
```
methods  fields   package/class name
42       1        android
2        0        android.app
3        0        android.content
2        0        android.content.res
2        1        android.graphics
2        0        android.graphics.drawable
6        0        android.text
1        0        android.text.style
4        0        android.view
1        0        android.view.animation
25       0        android.widget
101      53       com
100      53       com.basgeekball
100      53       com.basgeekball.awesomevalidation
7        2        com.basgeekball.awesomevalidation.helper
4        2        com.basgeekball.awesomevalidation.model
10       8        com.basgeekball.awesomevalidation.utility
43       19       com.basgeekball.awesomevalidation.validators
1        0        com.google
1        0        com.google.common
1        0        com.google.common.collect
33       0        java
13       0        java.lang
6        0        java.math
14       0        java.util
6        0        java.util.regex
1        0        org
1        0        org.jacoco
1        0        org.jacoco.agent
1        0        org.jacoco.agent.rt
1        0        org.jacoco.agent.rt.internal_773e439
```

**Comment by thyrlian** [comment]
Just made another release v1.3.

The `consumerProguardFiles 'proguard-rules.pro'` is also required inside `library/build.gradle`.  This makes the application project merge library's ProGuard rules (which will strip unused Guava classes, and also Android classes).

Tested with [dex-method-counts](https://github.com/mihaip/dex-method-counts) on demo project's release APK:

```
Processing demo-release-unsigned.apk
Read in 10567 method IDs.
<root>: 10567
    <default>: 1
    android: 7631
        animation: 12
        app: 61
        content: 151
            pm: 14
            res: 79
        database: 18
        graphics: 175
            drawable: 85
                shapes: 1
        location: 5
        media: 1
        net: 13
        os: 59
        support: 6247
            a: 251
                a: 251
            v4: 2896
                a: 661
                b: 31
                    a: 2
                c: 206
                    a: 201
                d: 74
                    a: 74
                e: 2
                    a: 2
                f: 2
                g: 27
                h: 188
                i: 1044
                    a: 310
                widget: 661
            v7: 3100
                a: 629
                b: 1
                c: 55
                    a: 55
                d: 3
                e: 1
                view: 686
                    menu: 535
                widget: 1725
        text: 17
            style: 3
        transition: 17
        util: 33
        view: 471
            accessibility: 54
            animation: 20
            inputmethod: 2
        widget: 351
    com: 2501
        basgeekball: 134
            awesomevalidation: 134
                demo: 52
                helper: 5
                model: 3
                utility: 8
                validators: 36
        google: 2367
            common: 2367
                a: 2
                annotations: 3
                base: 936
                    internal: 7
                collect: 1426
    java: 421
        io: 18
        lang: 211
            ref: 10
            reflect: 13
        math: 7
        net: 3
        nio: 1
            charset: 1
        util: 181
            concurrent: 22
                atomic: 9
                locks: 1
            logging: 4
            regex: 9
    org: 12
        xmlpull: 12
            v1: 12
Overall method count: 10567
```

**Comment by thyrlian** [comment]
Thanks @mr-archano for the help of pointing out `consumerProguardFiles`.
