### ISSUE TITLE
We already have an EditText, can only have one Error 

### ISSUE THREAD

**Issue by sahilbnishkrant** [thyrlian/AwesomeValidation#20]
Showing Me error when i call mAwesomeValidator.validate() method 2nd Time

**Comment by thyrlian** [comment]
From my side, calling `validate()` more than one time doesn't have any problem.

Could you please be more specific about the details (some code, stacktrace and steps).

Thank you.

**Comment by sahilbnishkrant** [comment]
its work fine when i used ValidationStyle.BASIC  but when i used  ValidationStyle.UNDERLABEL  its Crashed My App with Error 
We already have an EditText, can only have one Error
even i put   EditText in  TextInputLayout

**Comment by thyrlian** [comment]
Sorry, but I just tried with the demo app, it worked fine.

The demo app contains many `EditText` fields, what I've tried just now is:
1. Fill some of them with valid input;
2. Leave some of them blank (invalid);
3. Fill some with invalid input;
4. Choose UNDERLABEL style;
5. Click SUBMIT button many times (which calls `mAwesomeValidation.validate();`), and corresponding error messages show up;
6. Click CLEAR button to reset all error messages;
7. Try again to click the SUBMIT button many times, and the proper error messages show again.

No problem, no crash.

If you could not show even some pseudo code or exact steps to reproduce, or any logs, then I have to say sorry that I really can't help.

Actually I suspect there is something else wrong which cause your crash, not necessarily from this library (which I tried totally fine).

Thanks.
