### ISSUE TITLE
Validation negative numbers.

### ISSUE THREAD

**Issue by Chellll** [thyrlian/AwesomeValidation#21]
Valid.addValidation(MyEditText,Range.closed(-20000f,20000f),"Err");

In MyEditText i typed -5 and it didn't validate.

**Comment by thyrlian** [comment]
Thanks for reporting, will check it later when I have time.

**Comment by Chellll** [comment]
change pattern
public static boolean isNumberFormat(String text) {
return Pattern.compile("^-?\d+(\.\d{1,6})?$").matcher(text).find(); 
}

**Comment by thyrlian** [comment]
Aha, so the problem is the negative number: the regex doesn't match the `minus`, right?

**Comment by Chellll** [comment]
yes

**Comment by thyrlian** [comment]
Sorry, then it's my bad, I'll correct it soon when I have time.  Sorry for any inconvenience.

**Comment by thyrlian** [comment]
Solved by commit "[Support negative numbers and add more unit tests](https://github.com/thyrlian/AwesomeValidation/commit/358d9da95a75a908d37c9843078063809052273d)", all unit tests are passed.
