### ISSUE TITLE
It can not work with "support.design.widget.TextInputLayout"

### ISSUE THREAD

**Issue by protectedMan** [thyrlian/AwesomeValidation#26]
if EditText surround with TextInputLayout,like this ->

```
<android.support.design.widget.TextInputLayout
                android:id="@+id/til_guangai_date"
                android:layout_width="match_parent"
                android:layout_height="wrap_content">
                <EditText
                    android:id="@+id/et_guangai_date"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:ems="10" />
            </android.support.design.widget.TextInputLayout>
```

This will trigger an exception ,Exception details：

> We already have an EditText, can only have one

**Comment by thyrlian** [comment]
Sorry, this library doesn't support `TextInputLayout` so far.  I planned to make it compatible with `TextInputLayout` and its validation style, but this requires significant API changes, and I don't have any time yet.  Thanks for your information.

**Comment by thyrlian** [comment]
Duplicated as https://github.com/thyrlian/AwesomeValidation/issues/13

**Comment by thyrlian** [comment]
Hi @protectedMan , I've been working on this feature last weekend, and just merged the feature branch to master.  It's well unit tested, and I plan to release it soon after updating README.  Thanks for your waiting and I'd be happy if you could try it out :)

**Comment by thyrlian** [comment]
Implemented by https://github.com/thyrlian/AwesomeValidation/pull/29
