### ISSUE TITLE
how to support confirm email  case

### ISSUE THREAD

**Issue by umutkinasolid** [thyrlian/AwesomeValidation#27]
I want to add confirm edittext if two edittext value not equal  I will show error message,

I think If I can show error message programmatically without any pattern I can do this  .

**Comment by thyrlian** [comment]
Hi @umutkinasolid , this feature is not implemented yet, thanks for reporting.  It seems like many developers want this feature, I'll definitely work on this.

**Comment by thyrlian** [comment]
Implemented by @Ilya-Gh (https://github.com/thyrlian/AwesomeValidation/pull/28).
