### ISSUE TITLE
Error adding validation

### ISSUE THREAD

**Issue by sunil-singh-chaudhary** [thyrlian/AwesomeValidation#30]
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 24: TypedValue{t=0x3/d=0x13a "res/color/secondary_text_material_light.xml" a=1 r=0x106011a}

on this line
    if (awesomeValidation.validate()) {}

**Comment by thyrlian** [comment]
It doesn't seem like the exception is thrown by the library (it never use or refer to `secondary_text_material_light`).  Could you please check again on your code side or share more stacktraces?  Thanks.

**Comment by DivyeshKalotra** [comment]
@sunil-singh-chaudhary  its cause because you ap <item name="android:textColorHighlight">@android:color/holo_red_dark</item>
        <item name="android:textColorLink">@android:color/holo_red_light</item>ply  theme and don't use these colors in theme
