### ISSUE TITLE
How do I add this library to my android project in eclipse?

### ISSUE THREAD

**Issue by atiaco2000** [thyrlian/AwesomeValidation#31]

**Comment by atiaco2000** [comment]
I can not find a way to add this library to my android project in eclipse

**Comment by thyrlian** [comment]
Sorry but it shouldn't be too much different from AndroidStudio.

Do you have **JCenter** repo included?

```
repositories {  
   jcenter()  
}
```

And also with the library added to your gradle dependencies?

```
dependencies {
    compile 'com.basgeekball:awesome-validation:2.0'
}
```

That should be it.

**Comment by atiaco2000** [comment]
I don't see any Grande in eclipse. Do you have the Jar file for this library?

**Comment by thyrlian** [comment]
Yep, you can find it [here](https://bintray.com/thyrlian/android-libraries/com.basgeekball.awesomevalidation/2.0#files/com/basgeekball/awesome-validation/2.0).  Just navigate to **Files** tab.

**Comment by atiaco2000** [comment]
I did add the jar file to my project but somehow it is unable to use

**Comment by thyrlian** [comment]
Sorry, my bad, the jar file there is indeed useless.

But you can try with attached jar file below (please unzip it to use).  Tested OK with Android Studio + gradle (`compile fileTree(dir: 'libs', include: '*.jar')`).

The **jar** file is actually converted from the **aar** file (which you can download from previous link).  Steps are pretty easy, you can do by yourself:
1. `unzip awesome-validation-2.0.aar`
2. `mv classes.jar awesome-validation-2.0.jar`
3. include the jar in your project

Apart from this, you could also try the '[Consuming AARs from Eclipse](https://commonsware.com/blog/2014/07/03/consuming-aars-eclipse.html)' approach.

[lib.zip](https://github.com/thyrlian/AwesomeValidation/files/901918/lib.zip)
