### ISSUE TITLE
Double Validation with different Error String

### ISSUE THREAD

**Issue by regifr** [thyrlian/AwesomeValidation#34]
can I use two or more validator in one TextInputLayout

`
validator.addValidation(this, R.id.tilEmail, RegexTemplate.NOT_EMPTY, R.string.err_email_null);
validator.addValidation(this, R.id.tilEmail, Patterns.EMAIL_ADDRESS, R.string.err_email);
`

while the tilEmail is EMPTY the error just showing Patterns.EMAIL_ADDRESS with err_email not err_email_null

**Comment by thyrlian** [comment]
@regifr 
* Yes, it doesn't support multiple validations on one field.  So in your case, the new one will overwrite the old one.
* The idea is to wrap all validation rules into one Regex, and bind it with a field.  And I've confirmed, `Patterns.EMAIL_ADDRESS` has already included validation for empty input.  Thus you don't need `RegexTemplate.NOT_EMPTY`.

**Comment by krhitesh** [comment]
Hey @thyrlian , I think this needs to be addressed. Can you please guide me on how to do it, just a high level overview will also work.

**Comment by thyrlian** [comment]
Hi @krhitesh, as I mentioned, instead of having two independent regex, please combine the matching rules into one regex, which could fulfill the requirements from both.
