### ISSUE TITLE
Custom color for UnderLabel mode

### ISSUE THREAD

**Issue by MatthieuFereyre** [thyrlian/AwesomeValidation#36]
It could be nice to allow the change of error color in underlabel mode (as in coloration mode).

**Comment by thyrlian** [comment]
Thanks @MatthieuFereyre.  You mean [this one](https://github.com/thyrlian/AwesomeValidation/blob/master/library/src/main/java/com/basgeekball/awesomevalidation/validators/UnderlabelValidator.java#L52)?

It's just a little weird to me if I see any error color other than red (just like the default error label of Android is red too).

But yes, I can change it to allowing setting different color (as you might have your own color theme).

**Comment by MatthieuFereyre** [comment]
Yes exactly. The code to add is almost the same as the coloration mode.

**Comment by thyrlian** [comment]
Implemented by [commit](https://github.com/thyrlian/AwesomeValidation/commit/fc669c30cdd8fef2650894cc574da885704cf564)
