### ISSUE TITLE
Don't validate invisible or gone fields

### ISSUE THREAD

**Issue by MatthieuFereyre** [thyrlian/AwesomeValidation#37]
When a field is gone or invisible, it is impossible for the user to fill it. 
Maybe it is possible to don't validate it ?

Validator.java; Method checkFields :

```Java
protected boolean checkFields(ValidationCallback callback)
{
        boolean result = true;
        mHasFailed = false;
        for (ValidationHolder validationHolder : mValidationHolderList)
        {
// Patch
           if (validationHolder.getEditText() != null
                && validationHolder.getEditText().getVisibility() != View.VISIBLE)
            {
                continue;
            }
// End Patch        

            if (validationHolder.isRegexType())
            ...
```

**Comment by thyrlian** [comment]
Good question.  Would you please share a use case?  I thought a field is always visible until the validation passes (then the whole view which contains the fields to be validated will be gone).

**Comment by MatthieuFereyre** [comment]
Imagine a form with a spinner representing an identity piece type. You can select none/driver licence/id card. If the user select something different than "none", you show a field to type the serial number for exemple.

**Comment by mr-day** [comment]
same here, sometime i passed some id to invisible edittext

**Comment by thyrlian** [comment]
Thanks @mr-day for the input, I'll start to work on this after I finish another issue with ConstraintLayout.

**Comment by mr-day** [comment]
Nice, I'm glad to hear that :)

**Comment by thyrlian** [comment]
This feature has been added to TODO list.

**Comment by thyrlian** [comment]
Implemented by [commit](https://github.com/thyrlian/AwesomeValidation/commit/33e8af9a0d7e0872749d28c1a1ac8281feca8350).
