### ISSUE TITLE
AwesomeValidation not working inside Fragment

### ISSUE THREAD

**Issue by aj019** [thyrlian/AwesomeValidation#38]
I am trying to use awesome validation in a fragment and it doesn't seem to work. I have previously used it in an activity and it works.

**Comment by thyrlian** [comment]
Hi @aj019, it should work with Fragment.  Please check the [comments](https://github.com/thyrlian/AwesomeValidation/issues/35#issuecomment-324466006) here.  Usually moving the `validate()` method from `onCreateView` to `onActivityCreated` would make it work.  Thanks.

**Comment by aj019** [comment]
Thanks @thyrlian  using onActivityCreated solved the problem

**Comment by thyrlian** [comment]
Cool @aj019 good to hear that.  I'll try to mention this in README.  Thanks again.
