### ISSUE TITLE
Radio Button Validation

### ISSUE THREAD

**Issue by vinc4** [thyrlian/AwesomeValidation#39]
Validate Radio Buttons

**Comment by thyrlian** [comment]
Hi @vinc4, thanks for the proposal.  Would you mind giving more details - How it should look like?  How to design the API?  That would be great.  Of course I can take some time to think about it.

**Comment by vinc4** [comment]
i cant validate Radio buttons and please help me how to validate username
textbox i just dont want it to be empty i do want it to have characters
also

**Comment by thyrlian** [comment]
Radio button is not supported so far.
Regarding username, could you please attach your layout.xml?

**Comment by vinc4** [comment]
its fine i had to validate my username using String regexUsername =
"^[a-z0-9_-]{3,15}$";

**Comment by thyrlian** [comment]
So username validation is working for you?

**Comment by vinc4** [comment]
Yes it is , thanks for your liblary i love yo work keep making more

**Comment by thyrlian** [comment]
Thank you for your compliment, I'll keep on improving :)
