### ISSUE TITLE
How to use in Fragment

### ISSUE THREAD

**Issue by DhinakaranSDK** [thyrlian/AwesomeValidation#40]
In Activity working fine. But how to Implement in Fragment. Tried but not working.

**Comment by thyrlian** [comment]
Hey, you can find **Fragment** usage guide in **README** as described like below:

> It works perfectly with **Fragment**, but please pay attention to Fragment's lifecycle. You should set the `validate()` inside Fragment's `onActivityCreated` instead of `onCreateView` or any other early stage.

**Comment by DhinakaranSDK** [comment]
@thyrlian Thankyou. Working fine

**Comment by thyrlian** [comment]
@DhinakaranSDK did you get a chance to try?

**Comment by thyrlian** [comment]
@DhinakaranSDK cool, good to hear that.
