### ISSUE TITLE
Required validation on ImageView

### ISSUE THREAD

**Issue by myeduapp** [thyrlian/AwesomeValidation#44]
I have used the library to validate Text-views in my android application.How to add Required validation for image view?(i.e if the image is not selected before submitting it should show error like profile image is required?).Is it possible to achieve by using this library?

**Comment by thyrlian** [comment]
Sorry, but this is not supported at the moment.

**Comment by thyrlian** [comment]
Now you can use `CustomValidation` to achieve the goal :)
