### ISSUE TITLE
Override for TextInputLayout seems broken

### ISSUE THREAD

**Issue by lordplagus02** [thyrlian/AwesomeValidation#47]
I am attempting to do something like the following, assuming `_clientNameInputLayout` has been initialized:
`addValidation(_clientNameInputLayout, RegexTemplate.NOT_EMPTY, R.string.field_required)`
but I'm getting this error: 

> cannot resolve method 'addValidation(TextInputLayout, String, int)'

However, if I do the following:
`addValidation(_clientNameInputLayout, RegexTemplate.NOT_EMPTY, "This field is required")`
the compiler is happy.
Surely my initial statement should be allowed? Or am I doing something stupid?

**Comment by thyrlian** [comment]
It's by design.

You can either pass the **resource ID** for both the field and error message, like this:

```
addValidation(R.id.clientName, RegexTemplate.NOT_EMPTY, R.string.field_required);
```

Or pass **object** for both the field and error message, like this:

```
addValidation(_clientNameInputLayout, RegexTemplate.NOT_EMPTY, "This field is required");
```

But unfortunately you can't not pass them in a mixed way like what you did at the first try.

**Comment by lordplagus02** [comment]
What is the reasoning behind this design choice?

**Comment by thyrlian** [comment]
The reason is:
* Either you have the `context`, then you could simply pass the resource `id` and `string`, the library code would get the resource on behalf of you.
* Without knowing the `context`, you just pass the view object itself and the validation message string.

Thanks.
