### ISSUE TITLE
How to add multiple validations

### ISSUE THREAD

**Issue by kcdhaker1987** [thyrlian/AwesomeValidation#48]
I want to add two validations like first one is RegexTemplate.NOT_EMPTY and second one is required length
but it's showing only second validation message on validate , but i want to saw only first  RegexTemplate.NOT_EMPTY message if field is empty.

How can i do this?

**Comment by thyrlian** [comment]
Hi, you can directly use regex to meet you requirement (don't add multiple validations for one field separately, the last one will override all before).  So just combine `NOT_EMPTY` and `LENGTH_LONGER_THAN` into one regex would work.
