### ISSUE TITLE
awesomeValidation doesnot work on fragment...

### ISSUE THREAD

**Issue by keshavbhusal1** [thyrlian/AwesomeValidation#49]
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        mainView = inflater.inflate(R.layout.fragment_feedback, container, false);

        initView();

        return mainView;
    }

    private void initView(){

        editEmail = (EditText) mainView.findViewById(R.id.edit_email);
        editMessage = (EditText) mainView.findViewById(R.id.edit_message);
        btnSend = (Button) mainView.findViewById(R.id.btn_send);
        coordinatorLayout = (CoordinatorLayout) mainView.findViewById(R.id.coordinatorLayout);
        snackBar = new SnackBar();

        awesomeValidation = new AwesomeValidation(UNDERLABEL);

        awesomeValidation.setContext(getContext());
        btnSend.setOnClickListener(this);
        addValidationToViews();

    }

    @Override
    public void onClick(View view) {

        switch (view.getId()){

            case R.id.btn_send:

                if (awesomeValidation.validate()) {

               Toast.makeText(getContext(), "FeedBack Validation", Toast.LENGTH_SHORT).show();

                }

                break;
        }
    }

    private void addValidationToViews(){

        awesomeValidation.addValidation(getActivity(),R.id.edit_email, Patterns.EMAIL_ADDRESS, R.string.invalid_email);
        awesomeValidation.addValidation(getActivity(), R.id.edit_message, RegexTemplate.NOT_EMPTY, R.string.invalid_name);

    }
///////////////////////////////////////////////
always return true.

**Comment by thyrlian** [comment]
Hi @keshavbhusal1 , it's not an issue.  Please check the README of how to use it properly with Fragment.  Thanks.

> It works perfectly with Fragment, but please pay attention to Fragment's lifecycle. You should set the `validate()` inside Fragment's `onActivityCreated` instead of `onCreateView` or any other early stage.

Good luck and have fun :)

**Comment by keshavbhusal1** [comment]
thank you it work for me

**Comment by thyrlian** [comment]
Cool, good to hear :)
