### ISSUE TITLE
Label space not removed after invalid to valid state

### ISSUE THREAD

**Issue by lordplagus02** [thyrlian/AwesomeValidation#58]
Me again. I'm using the TextInputLayout style in this case.

Upon failed validation, the red labels appear below fields as they should, however when the user inputs valid data, if there are still validation errors, the space where the valid field's error label used to be doesn't close or disappear, causing an unwanted gap between fields in my LinearLayout dialog form.

Here is a screenshot, whereby the name field was invalid until entering Bob Jones, but the email field is still invalid and the space beneath Bob Jones still remains.
![20180219_172322](https://user-images.githubusercontent.com/11164562/36384973-cfb8df9a-1599-11e8-88d8-7a4553418017.png)

**Comment by thyrlian** [comment]
Hi @lordplagus02, yes, it's a known issue.  And actually it's an issue from `TextInputLayout` side, I didn't do anything special to create / remove the space.  So far I don't really know how to solve the problem, but I promise I would try my best.  Thanks.

**Comment by thyrlian** [comment]
Or if you can't live with the annoying space any more, you could try `UNDERLABEL` style :)

**Comment by thyrlian** [comment]
Sorry @lordplagus02, turned out an easy fix:

`textInputLayout.setErrorEnabled(false);`

Fixed by [commit](https://github.com/thyrlian/AwesomeValidation/commit/eb089aa49e7ea76547917cda845c642f75d92621), will be released soon with v4.1

Thanks and have fun :)
