### ISSUE TITLE
How to simply say that a field is required?

### ISSUE THREAD

**Issue by sarbogast** [thyrlian/AwesomeValidation#59]
For most of my textedit fields, the only constraint is that they cannot be blank. Is there a way to simply specify that constraint, without going through an overkill regex? Because I didn't find any example of that in the sample app, or in the README.

**Comment by thyrlian** [comment]
True, in that case regex is a bit overkill :(

Would you mind creating a PR, with an enum type let's say `NOT_EMPTY`, and API like this?

```java
mAwesomeValidation.addValidation(activity, R.id.edt_comment, Restriction.NOT_EMPTY, R.string.err_comment);
```

Thanks.

**Comment by sarbogast** [comment]
I'm too much of a noob in Android dev to propose any kind of PR, but that would be nice indeed. :-P

**Comment by thyrlian** [comment]
No problem, I'll try it when I have time.  But for the time being, please keep on using the annoying regex.  Thanks :)

**Comment by thyrlian** [comment]
Sorry, my bad, that would increase the complexity.

And now I just remembered that actually there is already a simple alternative solution in place.  Just like mentioned in README:

```java
mAwesomeValidation.addValidation(activity, R.id.edt_tel, RegexTemplate.TELEPHONE, R.string.err_tel);
```

Similarly, you can use the built-in [`RegexTemplate.NOT_EMPTY`](https://github.com/thyrlian/AwesomeValidation/blob/master/library/src/main/java/com/basgeekball/awesomevalidation/utility/RegexTemplate.java).
