### ISSUE TITLE
Gradle can't download your library

### ISSUE THREAD

**Issue by consulpro** [thyrlian/AwesomeValidation#6]
I write " compile 'com.github.thyrlian:AwesomeValidation:3ef10cd2c8' '' 
in my build.gradle file, but it prompts this: 
"Failed to resolve: com.github.thyrlian:AwesomeValidation:3ef10cd2c8

Can anyone help me with this error?

**Comment by thyrlian** [comment]
Sorry @consulpro .

I haven't tested if this import approach provided by Android Arsenal is working or not.  But if not, I'm still working on publishing it to Maven Central (will be done soon).  Actually now it's already on [jCenter](https://bintray.com/thyrlian/android-libraries/com.strohwitwer.awesomevalidation/view).  Maybe for the time being you could just try to use the jar, and later next week you could use it from Maven Central.  Thanks.

**Comment by thyrlian** [comment]
Just updated README, now it's fully working from JCenter, you could try adding below to your gradle's dependencies:
```java
compile 'com.basgeekball:awesome-validation:1.0'
```
