### ISSUE TITLE
Annotation support required

### ISSUE THREAD

**Issue by Sumit-Chakole** [thyrlian/AwesomeValidation#60]
Add Validation code is too verbose, may you add annotation support here

**Comment by thyrlian** [comment]
Not everything needs Annotation.

Add validation code is already dead simple (one-liner), annotation won't help much.

```
mAwesomeValidation.addValidation(activity, R.id.edt_tel, RegexTemplate.TELEPHONE, R.string.err_tel);
```

Thanks anyway.
