### ISSUE TITLE
Custom error color on TEXT_INPUT_LAYOUT

### ISSUE THREAD

**Issue by itryp** [thyrlian/AwesomeValidation#63]
Hi,

You are using your own style on the class TextInputLayoutValidator : https://github.com/thyrlian/AwesomeValidation/blob/7c7681f95bfa4f79b442f36b6b84da1260f07f81/library/src/main/java/com/basgeekball/awesomevalidation/validators/TextInputLayoutValidator.java#L17

Using TEXT_INPUT_LAYOUT, we cannot use the application's style for the error message color because it's overrided by your own style.

Thank you :)

**Comment by thyrlian** [comment]
Yep, you're right, it's using its own style, which actually only contains a color attribute:
https://github.com/thyrlian/AwesomeValidation/blob/master/library/src/main/res/values/styles.xml#L4

Could you please help create a PR for this?  Make the color settable for `AwesomeValidation` object with `TEXT_INPUT_LAYOUT ` type.  Thanks in advance.

**Comment by thyrlian** [comment]
Thanks for the PR, I just checked and merged.  Will close this issue.

But please keep in mind that this fix will not be available until next release.  Or you can simply add the dependency from `JitPack` by using the specific git commit hash version (please check the README for more details).

**Comment by itryp** [comment]
Thank you for merging and for your work on this awesome validator. If it can help someone, to use the updated version with the last commit : 

 implementation 'com.github.thyrlian:AwesomeValidation:da0d0fa1fba88c64f97bfed2f81adfede8c82bbc'
