### ISSUE TITLE
Add simple custom validation function

### ISSUE THREAD

**Issue by FiorikaSW** [thyrlian/AwesomeValidation#68]
The library is really helpfull. But it is not very clear how to create a custom validation function from the documentation. It seems not to have the  SimpleCustomValidation interface. Should I create it?

**Comment by thyrlian** [comment]
I don't know why you're saying "it is not very clear"?

As the README doc clearly pointed out: after you import the dependency by `implementation 'com.basgeekball:awesome-validation:4.2'`, the [`SimpleCustomValidation`](https://github.com/thyrlian/AwesomeValidation/blob/master/library/src/main/java/com/basgeekball/awesomevalidation/utility/custom/SimpleCustomValidation.java) interface will be available.  And how to use is also documented in the [Sample Code](https://github.com/thyrlian/AwesomeValidation#sample-code), in the section of "***to validate with a simple custom validator function***".
