### ISSUE TITLE
not empty validation

### ISSUE THREAD

**Issue by linger1216** [thyrlian/AwesomeValidation#7]
have not empty validation

**Comment by thyrlian** [comment]
Thanks for your great information, I'll check it later today :)

**Comment by thyrlian** [comment]
I added a regex to RegexTemplate, you could use it for validating a field not being empty.

But before making another release to JCenter, I think you can just simply use `"^(?=\\s*\\S).*$"`.

Thanks.

**Comment by linger1216** [comment]
I have cellphone EditText.  

the valid condition: not empty and only number and length = 11 

mAwesomeValidation.addValidation((EditText)getView(R.id.cellphone), ???, "电话号码格式不正确");

Thanks a lot

**Comment by thyrlian** [comment]
This regex should work:
"[0-9]{11}?"

Have fun :)
