### ISSUE TITLE
Error: Program type already present: com.google.thirdparty.publicsuffix.PublicSuffixPatterns

### ISSUE THREAD

**Issue by DohaBasem** [thyrlian/AwesomeValidation#70]
After adding the library dependency to my app gradle ,I got this error  "Error: Program type already present: com.google.thirdparty.publicsuffix.PublicSuffixPatterns" .I am using Android Studio 3.2 and build tools 28.0.2 . Any help or explanation for the cause of this error is highly appreciated as I need this urgently.

**Comment by thyrlian** [comment]
Please use `gradlew <your_app_module>:dependencies` to list all your dependencies, or use `gradlew lib:dependencies` to list this library's dependencies (it seems like from *guava*).  Find out which one uses `com.google.thirdparty.publicsuffix`.

Then try to exclude the module within one of it, from the guava implementation.
