### ISSUE TITLE
Offer the option to use validation in Fragments

### ISSUE THREAD

**Issue by carstenbaumhoegger** [thyrlian/AwesomeValidation#8]
It would be great if this library would offer the option to simply use the `addValidation` methods in Fragments! :)

**Comment by thyrlian** [comment]
Hello Carsten, thank you very much for your request.

In fact, you could directly use AwesomeValidation in either Fragment class or Activity class (with views from fragment).

Examples:
* if you want to validate in Activity class (very simple):
```java
mAwesomeValidation.addValidation(activity, R.id.view_in_fragment, "regex", R.string.err_message);
```

* if you want to validate in Fragment class:
```java
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_layout, container, false);
        EditText edt = (EditText) view.findViewById(R.id.edt_in_fragment);
        Button btn = (Button) view.findViewById(R.id.btn_in_fragment);
        mAwesomeValidation = new AwesomeValidation(BASIC);
        mAwesomeValidation.addValidation(edt, "regex", "error message");
        btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mAwesomeValidation.validate();
            }
        });
        return view;
    }
```

Tested OK with Android 4.3 (API level 18).

**Comment by carstenbaumhoegger** [comment]
Hello Jing,
thanks for the code samples, I tried to add the validation before onCreateView in Fragments, that was my (very stupid) fault :D
I really like this library, keep up the good work! :) :+1:

**Comment by thyrlian** [comment]
Hello Carsten,
Good to know it works for you, and I'm really happy that you like it, thanks :)
