### ISSUE TITLE
Debugging is not working in Andorid studio with use of Awesome validation in debug builds 

### ISSUE THREAD

**Issue by johnsonkhristi** [thyrlian/AwesomeValidation#80]
I am experience issues with debugging with the use of awesome validation. With debug builds when minifyEnable is true breakpoints are not being hit. 

The surprising thing is after removing awesome validation debugging is working. 

I have a request to the library developers to please check the cause and suggest a correct solution upon it.

**Comment by thyrlian** [comment]
Yes, I've configured `minifyEnabled` [here](https://github.com/thyrlian/AwesomeValidation/blob/master/library/build.gradle#L19-L24).  It is set to `false` for debug build, and `true` for release build.

> With debug builds when minifyEnable is true breakpoints are not being hit.
Why not use `false` for this case?

> after removing awesome validation debugging is working.
You can try to import a [JitPack version](https://github.com/thyrlian/AwesomeValidation#import-as-dependency), as it should be a debug build without minifyEnabled on.

**Comment by johnsonkhristi** [comment]
I have tried two things  as you recommended: 

1. With  JitPack version with minifyEnabled, it has the same issue (I think with minifyEnable it should have to work too)

2. I added the library as a modular dependency in the sample demo app to test it around and have a change configuration  (minifyEnable true in debug build). 

In both cases debugging is not working, I think its issue with the proguard rules you are using can you please ensure.

**Comment by thyrlian** [comment]
`minifyEnable` should be false, so that it doesn't obfuscate any source code.
