### ISSUE TITLE
Library is not building when i have viewpager2 in my project

### ISSUE THREAD

**Issue by BhargaviDeviYamanuri** [thyrlian/AwesomeValidation#81]
In my project i have viewpager2, when i try to add the awesome validation library im getting bellow error when sync now is happening.

Failed to resolve: androidx.viewpager2:viewpager2:4.2

**Comment by thyrlian** [comment]
Hi @BhargaviDeviYamanuri, I apologize for my late reply.  But I can't reproduce what happened to you on my side, in fact, I don't have any issue using this library together with ViewPager2.  Below is what I've tried:

* Clone the official Android ViewPager2 sample project from [here](https://github.com/android/views-widgets-samples/tree/master/ViewPager2).
* Update all dependencies in `build.gradle` as below, and also add this library:
  ```
  apply plugin: 'com.android.application'
  apply plugin: 'kotlin-android'
  apply plugin: 'kotlin-android-extensions'

  android {
      compileSdkVersion 28
      defaultConfig {
          applicationId "com.example.androidx.viewpager2"
          minSdkVersion 14
          targetSdkVersion 28
          versionCode 1
          versionName "1.0"
          testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
      }

      compileOptions {
          sourceCompatibility 1.8
          targetCompatibility 1.8
      }

      kotlinOptions {
          jvmTarget = "1.8"
      }

      buildTypes {
          release {
              minifyEnabled false
              proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
          }
      }
  }

  dependencies {
      implementation fileTree(dir: 'libs', include: ['*.jar'])
      implementation 'androidx.viewpager2:viewpager2:1.0.0'
      implementation 'androidx.fragment:fragment-ktx:1.3.0-alpha08'
      implementation 'com.google.android.material:material:1.3.0-alpha02'
      implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.72'
      implementation 'com.basgeekball:awesome-validation:4.2'

      // Testing dependencies
      androidTestImplementation 'androidx.test:rules:1.3.0'
      androidTestImplementation 'androidx.test.ext:junit:1.1.2'
      androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
  }
  ```
* Make sure to enable AndroidX property in `gradle.properties`:
  ```
  android.useAndroidX=true
  android.enableJetifier=true
  ```

I can run the project flawlessly.

Here I'm using the latest **ViewPager2**:
  `androidx.viewpager2:viewpager2:1.0.0`
however, I've noticed that you're using:
  `androidx.viewpager2:viewpager2:4.2`

I'm afraid that version doesn't exist, maybe that's the cause of your dependency resolution problem.  Could you please double-check and try a different version?
