### ISSUE TITLE
Release to maven central

### ISSUE THREAD

**Issue by om26er** [thyrlian/AwesomeValidation#85]
JCenter/Bintray is going away. Please upload AwesomeValidation to maven central

**Comment by thyrlian** [comment]
Yep, was aware of that, planned to do it but haven't got time, will do.  Thanks for the reminder.

**Comment by thyrlian** [comment]
Will publish to Maven Central:
https://issues.sonatype.org/browse/OSSRH-68174

https://github.com/thyrlian/AwesomeValidation/issues/3

**Comment by thyrlian** [comment]
Migrated all previous versions from Bintray to [Maven Central](https://search.maven.org/artifact/com.basgeekball/awesome-validation), also released a new version [4.3](https://github.com/thyrlian/AwesomeValidation/releases/tag/v4.3).
