### ISSUE TITLE
Help creating Regex for custom use cases

### ISSUE THREAD

**Issue by rk8339811** [thyrlian/AwesomeValidation#86]
Hi,

In my Android App, I am planning to use this Library for validating user input such as Email, name, etc. This library provides an option to validate the input with custom parameters by providing a custom Regex.

This is a great, simple, and easy-to-use library.

I am new to the Regex topic hence wanted help building Regex for the below use cases:

**Name:** Min 4 characters and Max 50 Characters. Can be in any language and can have any characters.

**Username:** Min 3 characters and Max 15 Characters. Should only be in English Language and only alphabets, numbers, and "_" (underscore) should be allowed.

**Password:** Min 8 characters and Max 50 Characters. Should only be in English Language and should have at least one Captial Letter, at least one Small Letter, at least one Number, and At least one special character. And no Emoji should be allowed.

**Bio:** Min 10 characters and max 160 characters. Any Language allowed with any text and (if possible) no Link should be allowed.

**Email:** Min 5 characters and max 100 characters. It should be a valid email format in English Language only.

I shall be using this Regex within my Android Java written using Java.

It would be great if anyone could help create the above Regex. Please let me know if this is off-topic I shall close this issue.

Thanks.

**Comment by thyrlian** [comment]
Thanks for using the library, and sorry for my late response.

I believe that in the past few months, you've managed to compose regex for the above cases.  And I just want to mention as well that there are many online regex editor tools that you can utilize with a trial-and-error approach (e.g.: [Regular Expression Test Page for Java](https://www.regexplanet.com/advanced/java/index.html)).

Happy hacking.
