### ISSUE TITLE
Range for hours

### ISSUE THREAD

**Issue by mehdibaha** [thyrlian/AwesomeValidation#9]
Hi,
I'm trying to implement a validation for a TimePickerDialog, and I didn't find a way to properly set a Range, while showing a nice text on the EditText. 
Here's my code :
    mAwesomeValidation.addValidation(this, R.id.time, Range.closed(hour, hour +      MAX_DURATION_PARTY_IN_HOURS), R.string.err_time);
To resolve the issue, I have to set the EditText to just the "hour", and I noticed in the code you validate based on the EditText, so how could I solve this issue ?
Thank you.

**Comment by thyrlian** [comment]
Hi,

Thanks for your feedback.

Do you mean that actually you want to validate one view widget, and then show the visual feedback on another view?

Could you please upload a screenshot of your layout?  That may help me understand what exactly you wanna achieve.

Best,
Jing

**Comment by spiritus1** [comment]
I have an EditText, which shows a TimePicker when onClick, i want to show
the underline in the ET, based on TP, whild showing whayever I want in ET

**Comment by thyrlian** [comment]
OK, so you want to validate and show feedback on two different view widgets.

Sorry, I don't think it's possible to do what you want with the current version.  But I'll think about it after work or maybe during the weekend.

Thanks.

**Comment by spiritus1** [comment]
Thanks a lot !

**Comment by thyrlian** [comment]
Now you can use `CustomValidation` to achieve the goal :)
