### ISSUE TITLE
The listener for all validation results

### ISSUE THREAD

**Issue by XiaoRanLiu3119** [thyrlian/AwesomeValidation#90]
How can I get the listener for all validation results to control the button clickable

**Comment by thyrlian** [comment]
Hey @XiaoRanLiu3119 

You can take a look at the [example in README](https://github.com/thyrlian/AwesomeValidation#sample-code) or read the source code directly.  It's quite straightforward.

* Just trigger the validation by `mAwesomeValidation.validate()`, which would highlight the invalid field(s), and most importantly, the `validate()` method returns a boolean if all fields passed or any of them failed (source code is [here](https://github.com/thyrlian/AwesomeValidation/blob/master/library/src/main/java/com/basgeekball/awesomevalidation/AwesomeValidation.java#L191-L193)).  Based on the boolean value, you can decide your button's clickable status.  Please bear in mind, there is no onTextChangeListener to monitor the typing dynamically, you have to trigger the validation by some action (a.k.a. when user confirms that he/she finishes).
* If you want to reset any view's status, please call `mAwesomeValidation.clear()`, its source code is [here](https://github.com/thyrlian/AwesomeValidation/blob/master/library/src/main/java/com/basgeekball/awesomevalidation/AwesomeValidation.java#L195-L197).
